### PR TITLE
fix: datetime console log

### LINKED ISSUE #1: Implement date time picker

### PR DESCRIPTION
**Pull request by sanukumarNS**

### CODE REVIEW

File: src/components/dashboard/settings/index.tsx [hunk 1]
```diff
@@ -7,7 +7,6 @@ const Settings = () => {
   const [selectedDate, setSelectedDate] = useState();
   const onChangeDate = (event, date) => {
     setSelectedDate(JSON.stringify(date));
-    console.log(date);
```
Comment (sanukumarNS) [inline src/components/dashboard/settings/index.tsx:10]: not the desired behavior
